name: 获取V2ray订阅
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
    watch:
      types: started
    repository_dispatch:
      types: get_v2ray
jobs:
  get_v2ray:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requests'
        run: |
          pip install -r requirements.txt
      - name: 设置githup信息
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
      
      - name: 获取订阅
        run: |
          python3 get_clash.py
          git add .
          git pull
          git commit --allow-empty -m "up"
          git push
      - name: 同步到gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/ronghuaxueleng
          dst: gitee/getready
          static_list: "get_v2"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
      - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1
